FIND_PROGRAM(CSCOPE_EXECUTABLE NAMES cscope)

IF (CSCOPE_EXECUTABLE)
		SET(CSCOPE_FOUND TRUE)
ENDIF(CSCOPE_EXECUTABLE)

IF (CSCOPE_FOUND)
		# show which CCtags was found only if not quiet
		IF (NOT CScope_FIND_QUIETLY)
				MESSAGE(STATUS "Found CScope: ${CSCOPE_EXECUTABLE}")
		ENDIF (NOT CScope_FIND_QUIETLY)
ELSE (CSCOPE_FOUND)
		# fatal error if CScope is required but not found
		IF (CScope_FIND_REQUIRED)
				MESSAGE(FATAL_ERROR "Could NOT find CScope")
		ELSEIF(NOT CScope_FIND_QUIETLY)
				MESSAGE(STATUS "Could NOT find CScope (missing: CSCOPE_EXECUTABLE)")
		ENDIF (CScope_FIND_REQUIRED)
ENDIF (CSCOPE_FOUND)
